// AF1AppApiRest/src/app/table/table.component.ts
import { Component, OnInit, SimpleChanges, ChangeDetectorRef} from '@angular/core';
import {Router} from '@angular/router';

import { ApiService } from '../api.service';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']

})
export class TableComponent implements OnInit {

  racesArray=[];
  seleccionadoOption:any;
  clasificacion:any=[];
  
  constructor(public api:ApiService, private router:Router) {}

ngOnInit(): void {
  console.log("NGINIT");

  //Obtenemos races Array para Select
  this.api.getRaces().subscribe((listaRaces:any) =>{

    console.log("ListaRaces "+listaRaces);
    this.racesArray=listaRaces;
    this.seleccionadoOption=this.racesArray[0];

    //Pintamos Global
    this.consultarDatos();
  });

   
   
}

consultarDatos():void{

  if(this.seleccionadoOption==="Global"){

    this.api.getRankingGlobal().subscribe((lista:any)=>{
      this.clasificacion=lista;
    });
  }else{
    this.api.getRankingCarrera(this.seleccionadoOption).subscribe((lista:any)=>{
      this.clasificacion=lista;
    });
  }
}

  //Cuando cambia el select volvemos a consultar datos
  onChangeSelect():void{
    this.consultarDatos();
  }

  //Navigate to user component
  userInfo(id:any):void{
   this.router.navigate(['/piloto',id]);
  }

}


<div class="positionRanking">
    <h5><i>Ranking / {{seleccionadoOption}} </i></h5>

      <select name="miselect" [(ngModel)]="seleccionadoOption" class="button-right" (change)="onChangeSelect()">
        <option [value]="" disabled selected hidden>Elige la clasificacion</option>
        <option [value]="item" *ngFor="let item of racesArray">{{item}}</option>
      </select>
    
  </div>
  
        <div class="table-responsive">
        <table>
            <thead class="tableColorVede">
            <tr>
              <th scope="col" class="bordeIz"></th>
              <th scope="col"><i>Rank</i></th>
              <th scope="col"><i>Name</i></th>
              <th scope="col" class="bordeDr"><i>Team</i></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let item of clasificacion; index as i" (click)="userInfo(item.id)" >
              <td>
                <img [src]="item.picture" class="me-1" style="width: 20px">
              </td>
              <td>
                <img *ngIf="i+1==1" src="../../assets/numero-uno.png" class="me-1" style="width: 15px">
                <img *ngIf="i+1==2" src="../../assets/numero-2.png" class="me-1" style="width: 15px">
                <img *ngIf="i+1==3" src="../../assets/numero-3.png" class="me-1" style="width: 15px">
                <p *ngIf="i+1>=4">{{ i+1}}</p>
              </td>
              <td>{{ item.name }}</td>
              <td>{{ item.team }}</td>
            </tr>
            </tbody>
          </table>
        </div>

// Stencil/af1stencil/src/components/table/table.tsx
import { Component,State,Event, h, EventEmitter} from '@stencil/core';

@Component({
  tag: 'app-table',
  styleUrl: 'table.css',
  shadow: false,
})
export class MyComponent {
    
  @State() clasificacion:any=[];
  @State() seleccionadoOption:any;
  @State() racesArray=[];
  @Event() goPagePilot: EventEmitter<any>;

  eventClickPilot(piloto:any){

    this.goPagePilot.emit(piloto);
  }

  componentDidLoad(){
    console.log('Entro')

    this.getRaces();
    this.consultarDatos("Global");
  }

  
  consultarDatos(race:string):void{
      this.seleccionadoOption=race;

    if(this.seleccionadoOption==="Global"){
    console.log("Entro consultarGlobal");
      this.getGlobalRank();
    }else{
        console.log("Entro consultarCarrera");
      this.getRankingCarrera(this.seleccionadoOption);
    }
  }
  
  handleSecondSelect(event) {
      console.log("CambioSelect "+event.target.value)
    console.log(event.target.value);
    this.seleccionadoOption= event.target.value;
    this.consultarDatos(this.seleccionadoOption);

  }

  async getRaces(){
    let response = await fetch('http://localhost:9000/races');
    this.racesArray = await response.json();


  }
  async getGlobalRank() {
    
  let response = await fetch('http://localhost:9000/ranking');
  this.clasificacion = await response.json();
 
  
 }

 async getRankingCarrera(carrera:string) {
    
  let response = await fetch("http://localhost:9000/ranking/carrera?carrera="+carrera);
  this.clasificacion = await response.json();
  
 }
 


  render() {
    return <div>
      <div class="inLine">
      <h3 class="positionRanking"><i>Ranking / {this.seleccionadoOption}</i></h3>

      <select name="miselect" class="button-right" onInput={(event) => this.handleSecondSelect(event)}>
        <option value="" disabled selected hidden>Elige la clasificacion</option>
        {this.racesArray.map((race:any) =>
          <option value={race}>{race}</option>
        )}
      </select>
    
      </div>

      <div>
      <div class="table-responsive">
        <table>
            <thead class="tableColorVede">
            <tr>
              <th scope="col" class="bordeIz"></th>
              <th scope="col"><i>Rank</i></th>
              <th scope="col"><i>Name</i></th>
              <th scope="col" class="bordeDr"><i>Team</i></th>
            </tr>
            </thead>
            <tbody>
              {this.clasificacion.map((piloto:any, index)=>
              <tr onClick={()=>this.eventClickPilot(piloto)}>
              <td><img src={piloto.picture} class="me-1"></img></td>
              <td>
                <p>{index+1}</p>
              </td>
              <td>{ piloto.name }</td>
              <td>{ piloto.team }</td>
            </tr>
               )}
            </tbody>
          </table>
        </div>
      </div>

    </div>;
  }


  
}
